/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_dep;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return StringUtils.upperCase("Hello World!");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
